### ISSUE TITLE
Force landscape orientation in AUICaptureController

### ISSUE THREAD

**Issue by proft** [abbyysdk/RTR-SDK.iOS#22]
Hi!

Is it possible to force landscape orientation inside AUICaptureController?
I mean camera view and all ui parts ("Close", "Keep still" hints).

I know it works in Android part of framework.
Or it is impossible in iOS part and I have to use AVCaptureSession?

**Comment by eugenebiryukov** [comment]
Hello, @proft !
Yes, this is possible.

You can subclass from the AUICaptureController and override its supportedInterfaceOrientations property, like this:
```
class LandscapedAUICaptureController: AUICaptureController {
    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return .landscape
    }
}
```

But you have to allow your application to support Landscape Left and/or Right orientations to make the AUICaptureController rotating. Otherwise, you'll receive "Supported orientations has no common orientation with the application, and [SampleAUICaptureController shouldAutorotate] is returning YES" exception, as per current Xcode 13.4.1 version.

In this case you'll need to restrict orientation changing in concrete controllers that are under the AUICaptureController, if it is needed.

**Comment by proft** [comment]
Thanks for your comprehensive answer!
